name: Version Created
on: 
  workflow_dispatch:

env:
  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  YELLOW: '\033[0;33m'
  PURPLE: '\033[0;35m'
  WHITE: '\033[0m'

jobs:
  test:
    name: 🔬 Run Test
    uses: spicyparrot/scan-images/.github/workflows/test.yml@trunk

  create_tag:
    name: 🏷 Create Tag
    runs-on: ubuntu-latest
    needs: [test]
    steps:    
      - name: Generate Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1    #https://github.com/marketplace/actions/github-tag
        with:
          github_token: ${{ github.token }}
          tag_prefix: "v"
          default_bump: minor
          #custom_tag: ${{ inputs.tag_name }}
          append_to_pre_release_tag: beta
          release_branches : trunk
      
      - name: Tag Details
        shell: bash
        run: |
          printf "${PURPLE}Tag Generated = ${{ steps.tag_version.outputs.new_tag }}\n"
          echo "Tag Generated = ${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_STEP_SUMMARY
       