name: ☢ Image Scanning

on:
  workflow_dispatch:
    inputs:
      image_grep:
        type: text
        default: python

jobs:
  scan:
    name: Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Load Test Images
        run: |
          docker pull python:3.4-alpine
          docker pull python:3.8.10-slim
          docker pull python:3.8.10

      - name: Scan Images
        uses: ./github/actions/scan
        with:
          image_grep: ${{ inputs.image_grep }}