name: 🧪 Test
on: 
  workflow_dispatch:
  workflow_call:

env:
  GREEN: '\033[0;32m'
  RED: '\033[0;31m'

jobs:
  python:
    name: 🐍 Python Images
    runs-on: ubuntu-latest
    steps:     
      - name: ⏬ Download Test Images
        run: |
          docker pull python:3.4-alpine
          docker pull python:3.8.10-slim
          docker pull python:3.8.10

      - name: ☢ Scan Images
        id: python
        uses: spicyparrot/scan-images@trunk
        with:
          image_grep: "python"
          severities: "CRITICAL"
          exit_on_error: false
      
      - name: 🚩 Set Job Output
        run: |
          echo "issues=${{ steps.python.outputs.issues }}" >> $GITHUB_OUTPUT
          printf "${RED} Issues found -  ${{ steps.python.outputs.issues }}\n"

  none:
    name: 🍌 No Matching Images
    runs-on: ubuntu-latest
    steps:     
      - name: ☢ Scan Images
        id: none
        uses: spicyparrot/scan-images@trunk
        with:
          image_grep: "bananaramallamadrama"
          severities: "CRITICAL"

      - name: 🚩 Set Job Output
        run: |
          echo "issues=${{ steps.none.outputs.issues }}" >> $GITHUB_OUTPUT
          printf "${RED} Issues found -  ${{ steps.none.outputs.issues }}\n"

  review:
    name: 🔍 Check Results
    runs-on: ubuntu-latest
    needs: [python, none]
    steps:
      - name: ✅ Check Outputs
        run: |
          printf "${RED} Python issues found -  ${{ needs.python.outputs.issues }}\n"
          printf "${RED} Empty match issues found -  ${{ needs.none.outputs.issues }}\n"

      - name: 🎌 Ensure Issues Found
        if: (needs.python.outputs.issues < 1) || (needs.none.outputs.issues > 0)
        uses: actions/github-script@v6.3.3
        with:
          script: core.setFailed('${{ steps.scan.outputs.issues }} issues found')

      - name: 🙌 Pass Unit Test
        run: |
          printf "${GREEN}Tests have passed! ✅"

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      #- name: Setup tmate session
      #  if: always()
      #  uses: mxschmitt/action-tmate@v3     #https://github.com/marketplace/actions/debugging-with-tmate  + https://blog.fleetdm.com/4-tips-for-github-actions-usability-2-debugging-4c0c920adfde
      #  timeout-minutes: 15     