name: 🧪 Test
on: 
  workflow_dispatch:
  workflow_call:
    
jobs:
  test:
    name: ☢ Test Scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        greps: ['python','bananaramallamadrama']
    steps:     
      - name: ⏬ Load Test Images
        run: |
          docker pull python:3.4-alpine
          docker pull python:3.8.10-slim
          docker pull python:3.8.10

      - name: ☢ Scan Images
        id: python
        uses: spicyparrot/scan-images@trunk
        if: always()  
        with:
          image_grep: "${{ matrix.greps }}"
          severities: "CRITICAL"
          
      - name: 🎌 Flag Scanning Errored Correctly
        if: (steps.python.outputs.total_issues > 0) || (steps.none.outputs.total_issues == 0)
        run: |
          echo "Python Issues - ${{ steps.python.outputs.total_issues }}"
          echo "No Matched Issues - ${{ steps.none.outputs.total_issues }}"

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      #- name: Setup tmate session
      #  if: always()
      #  uses: mxschmitt/action-tmate@v3     #https://github.com/marketplace/actions/debugging-with-tmate  + https://blog.fleetdm.com/4-tips-for-github-actions-usability-2-debugging-4c0c920adfde
      #  timeout-minutes: 15     