name: 🧪 Test
on: 
  workflow_dispatch:
  workflow_call:
    
jobs:
  test:
    name: ☢ Test Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        greps: ['python', 'bananaramallamadrama']
    steps:
      - name: 🛀 Checkout Self
        uses: actions/checkout@v3
      
      - name: ⏬ Load Test Images
        run: |
          docker pull python:3.4-alpine
          docker pull python:3.8.10-slim
          docker pull python:3.8.10

      - name: ☢ Scan Images
        id: python
        uses: spicyparrot/scan-images@trunk
        if: always()  
        with:
          image_grep: "${{ matrix.greps }}"
          severities: "CRITICAL"
          
      - name: 🎌 Flag Scanning Errored Correctly
        if: (steps.python.outputs.total_issues > 0) || (steps.none.outputs.total_issues > 0)
        run: |
          exit 1