name: 🧪 Test
on: 
  workflow_dispatch:
  workflow_call:

env:
  GREEN: '\033[0;32m'
  RED: '\033[0;31m'

jobs:
  python:
    name: 🐍 Python Images
    runs-on: ubuntu-latest
    steps:     
      - name: ⏬ Download Test Images
        run: |
          docker pull python:3.4-alpine
          docker pull python:3.8.10-slim
          docker pull python:3.8.10

      - name: ☢ Scan Images
        id: python
        uses: spicyparrot/scan-images@trunk
        with:
          image_grep: "python"
          severities: "CRITICAL"

  none:
    name: 🍌 No Matching Images
    runs-on: ubuntu-latest
    steps:     
      - name: ☢ Scan Images
        id: python
        uses: spicyparrot/scan-images@trunk
        with:
          image_grep: "bananaramallamadrama"
          severities: "CRITICAL"

  review:
    name: 🔍 Check Results
    runs-on: ubuntu-latest
    needs: [python, none]
    if: always()
    steps:               
      - name: 🎌 Ensure 1 Pass and 1 Fail
        if: (needs.python.result =='success') || (needs.none.result !='success')
        uses: actions/github-script@v6.3.3
        with:
          script: core.setFailed('${{ steps.scan.outputs.issues }} issues found')

      - name: 🙌 Pass Unit Test
        run: printf "${GREEN}Unit tests have passed! ✅"

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      #- name: Setup tmate session
      #  if: always()
      #  uses: mxschmitt/action-tmate@v3     #https://github.com/marketplace/actions/debugging-with-tmate  + https://blog.fleetdm.com/4-tips-for-github-actions-usability-2-debugging-4c0c920adfde
      #  timeout-minutes: 15     